License is being detected because a format problem was explained.  Now I am concerned the license actually has expired.
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Could not find any valid decoders in [clover.com.atlassian.extras.decoder.v2.Version2LicenseDecoder@13d7254, clover.com.atlassian.extras.decoder.v1.Version1LicenseDecoder@11d20d3] for license string <mpOmpVaNJDgMukslUanMdKLUMnQDhlfTcxHrRqTeNPBKljmi2K17NYtdSlFYvLGOxXY<mC2Kouo8xauo9avp8SlEsMyvoQMMsTRRponrONQMOmnUuqrqpOQnqOroPrWsxuvWUxxtsOnmpmUUnoupttummmmmmUUnoupttummmmmmUU1hrXZljUUn>
[INFO] ------------------------------------------------------------------------
[INFO] Trace
clover.com.atlassian.extras.decoder.api.LicenseDecoderNotFoundException: Could not find any valid decoders in [clover.com.atlassian.extras.decoder.v2.Version2LicenseDecoder@13d7254, clover.com.atlassian.extras.decoder.v1.Version1LicenseDecoder@11d20d3] for license string <mpOmpVaNJDgMukslUanMdKLUMnQDhlfTcxHrRqTeNPBKljmi2K17NYtdSlFYvLGOxXY<mC2Kouo8xauo9avp8SlEsMyvoQMMsTRRponrONQMOmnUuqrqpOQnqOroPrWsxuvWUxxtsOnmpmUUnoupttummmmmmUUnoupttummmmmmUU1hrXZljUUn>
        at clover.com.atlassian.extras.decoder.api.DelegatingLicenseDecoder.decode(DelegatingLicenseDecoder.java:47)
        at clover.com.atlassian.extras.core.DefaultLicenseManager.decodeLicense(DefaultLicenseManager.java:63)
        at clover.com.atlassian.extras.core.DefaultLicenseManager.getLicense(DefaultLicenseManager.java:48)
        at com.cenqua.clover.CloverLicense.<init>(CloverLicense.java:93)
        at com.cenqua.clover.CloverStartup$LicenseCertLoader.loadLicense(CloverStartup.java:291)
        at com.cenqua.clover.CloverStartup.loadLicense(CloverStartup.java:48)
        at com.cenqua.clover.CloverStartup.loadLicense(CloverStartup.java:25)
        at com.cenqua.clover.CloverInstr.mainImpl(CloverInstr.java:40)
        
ADMIN-15